### ISSUE TITLE
Concurrent executions causes InvalidOperationException 

### ISSUE THREAD

**Issue by blaze-byte** [francnuec/Neo4jClient.DataAnnotations#6]
Hi, 

While writing some integrations tests I got the below exception. It looks like there is a concurrency issue when multiple threads are trying to use the annotation library?

Maybe it has something to do with https://github.com/dotnet/runtime/issues/26868 ?

```
System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Neo4jClient.DataAnnotations.Utils.EntityTypeInfo.GetForeignKeysWithAttribute(Type attributeType)
   at Neo4jClient.DataAnnotations.Utils.Extensions.UnionNavPropsWithFKs(IEnumerable`1 navProps, EntityTypeInfo typeInfo, Type attributeToFilter, Func`2 fkFilter, List`1& FKs)
   at Neo4jClient.DataAnnotations.Cypher.Pattern.MergeNavPropsWithFKs(EntityTypeInfo typeInfo, List`1 navPropsOfSameType, Dictionary`2 navPropsDict, Type attributeToFilter)
   at Neo4jClient.DataAnnotations.Cypher.Pattern.GetNavPropertyFromNonInversePropertyAttribute(EntityTypeInfo typeInfo, List`1 navProps, Dictionary`2 navPropsDict, PropertyInfo knownInverseProperty)
   at Neo4jClient.DataAnnotations.Cypher.Pattern.GetNavigationPropertyBetweenTypes(EntityTypeInfo aTypeInfo, EntityTypeInfo bTypeInfo, PropertyInfo& inverseProperty, PropertyInfo knownNavProperty, Boolean assertColumnAttrHasName)
   at Neo4jClient.DataAnnotations.Cypher.Pattern.get_ABSelector()
   at Neo4jClient.DataAnnotations.Cypher.Pattern.get_ANavProperty()
   at Neo4jClient.DataAnnotations.Cypher.Pattern.ResolveRTypes(List`1 rTypes)
   at Neo4jClient.DataAnnotations.Cypher.Pattern.get_RTypes()
   at Neo4jClient.DataAnnotations.Cypher.Pattern.InternalBuild()
   at Neo4jClient.DataAnnotations.Cypher.Annotated.Build(ICypherFluentQuery& query)
   at Neo4jClient.DataAnnotations.Cypher.Path.<InternalBuild>b__15_0(Pattern p)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at Neo4jClient.DataAnnotations.Cypher.Path.InternalBuild()
   at Neo4jClient.DataAnnotations.Cypher.Annotated.Build(ICypherFluentQuery& query)
   at Neo4jClient.DataAnnotations.Cypher.PathBuilder.InternalBuild()
   at Neo4jClient.DataAnnotations.Cypher.CypherUtilities.BuildPaths(ICypherFluentQuery& query, IEnumerable`1 pathBuildExpressions, PropertiesBuildStrategy patternBuildStrategy)
   at Neo4jClient.DataAnnotations.CypherFluentQueryExtensions.WithPattern(ICypherFluentQuery query, String& pattern, PropertiesBuildStrategy defaultBuildStrategy, Expression`1[] patternDescriptions)
   at Neo4jClient.DataAnnotations.CypherFluentQueryExtensions.Match(ICypherFluentQuery query, Expression`1[] patternDescriptions)
```
If additional details are needed please let me know.

Thanks

**Comment by francnuec** [comment]
Hi,

Thanks for reporting this. I had concurrency issues too while writing tests initially, so I tried to handle most places I thought would generate errors. Obviously, I missed a few.

I am swamped with work atm, so I'm not really sure when I would be able to get to this yet (hopefully soon). I even just pushed an update out a few days ago addressing another issue when I was a little free. However, since this is just about locks, if you could take some time and add them to the remaining areas of the EntityInfo class and then send me a PR for it, I would appreciate that. That would make it easier for me to send out a quick patch.

Alternatively, for now, you might need to put locks on your EntityInfo instance around those tests having this issue to handle the exception. That being said, I don't think you should have this issue in normal use cases for your app. The concurrent nature of test runs is usually why this error comes up most times.
